    
version: "2"
 
services:
    nginx:
      container_name: nginx
      build: 
        context: .
        dockerfile: ./nginx.dockerfile
      links:
        - ghost1:ghost1
      ports:
        - "80:80"
        - "443:443"
      networks:
        - sf-network
      restart: always

    ghost1:
      container_name: ghost1
      build: 
        context: .
        dockerfile: ./ghost.dockerfile
      ports:
        - "2368:2368"
      environment:
        - "NODE_ENV=production"
        - "PORT=2368"
        - "MYURL=http://www.offthemainthread.co.uk"
      volumes:
        - /srv/docker/ghost/:/var/lib/ghost
      networks:
        - sf-network
      restart: always

    ghost2:
      container_name: ghost2
      build: 
        context: .
        dockerfile: ./ghost.dockerfile
      ports:
        - "3368:3368"
      environment:
        - "NODE_ENV=production"
        - "PORT=3368"
        - "MYURL=http://www.tech-kit.co.uk"
      volumes:
        - /srv/docker/ghost-other/:/var/lib/ghost
      networks:
        - sf-network
      restart: always

networks:
    sf-network:
      driver: bridge